


app:
  service:
    accuweather:
      searchCityUrl: http://dataservice.accuweather.com/locations/v1/search
      forecastUrl: http://dataservice.accuweather.com/forecasts/v1/daily/1day/{locationKey}
      apiKey: ${ACCUWEATHER_API_KEY}

    weatherStack:
      apiKey: ${WEATHER_STACK_API_KEY}

    openWeatherMap:
      apiKey: ${OPEN_WEATHER_MAP_API_KEY}